# Tomcat
server:
  port: 19100

spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        # 认证中心
        - id: iot-auth
          uri: lb://iot-auth
          predicates:
            - Path=/auth/**
          filters:
            # 验证码处理
            - CacheRequestFilter
            - ValidateCodeFilter
            - StripPrefix=1
        # 代码生成
        - id: iot-modules-gen
          uri: lb://iot-modules-gen
          predicates:
            - Path=/code/**
          filters:
            - StripPrefix=1
        # 定时任务
        - id: iot-modules-job
          uri: lb://iot-modules-job
          predicates:
            - Path=/schedule/**
          filters:
            - StripPrefix=1
        # 系统模块
        - id: iot-modules-system
          uri: lb://iot-modules-system
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1
        # 文件服务
        - id: iot-modules-file
          uri: lb://iot-modules-file
          predicates:
            - Path=/file/**
          filters:
            - StripPrefix=1
        # TDengine服务
        - id: iot-modules-tdengine
          uri: lb://iot-modules-tdengine
          predicates:
            - Path=/tdengine/**
          filters:
            - StripPrefix=1
        # Link服务
        - id: iot-modules-link
          uri: lb://iot-modules-link
          predicates:
            - Path=/link/**
          filters:
            - StripPrefix=1
        # Broker服务
        - id: iot-modules-broker
          uri: lb://iot-modules-broker
          predicates:
            - Path=/broker/**
          filters:
            - StripPrefix=1
            - RemoveRequestHeader=Sec-WebSocket-Protocol #移除请求头
        # ProtocolAnalysis服务
        - id: iot-modules-protocolAnalysis
          uri: lb://iot-modules-protocolAnalysis
          predicates:
            - Path=/protocolAnalysis/**
          filters:
            - StripPrefix=1
        # rule服务
        - id: iot-modules-rule
          uri: lb://iot-modules-rule
          predicates:
            - Path=/rule/**
          filters:
            - StripPrefix=1

# 安全配置
security:
  # 验证码
  captcha:
    enabled: true
    type: char
  # 防止XSS攻击
  xss:
    enabled: true
    excludeUrls:
      - /system/notice
  # 不校验白名单
  ignore:
    whites:
      - /auth/logout
      - /auth/login
      - /auth/register
      - /*/v2/api-docs
      - /csrf
      #MQTT消息推送接口
      - /broker/mqttBrokerOpen/sendMessage
      #客户端身份认证接口
      - /link/deviceOpenAny/clientConnectionAuthentication
      - /tdengine/**
